# Generated by Django 3.2.5 on 2021-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mob',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
