# Generated by Django 3.2.5 on 2021-07-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mob',
            new_name='contact_no',
        ),
    ]
